# Generated by Django 4.1.5 on 2023-10-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='media/default.png', upload_to='media/'),
        ),
    ]
